project_id = "mwtrdhnctzasddbeilwm"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions]
import_map = "./functions/_shared/import_map.json"

[functions.spotify-fetch]
verify_jwt = false

[functions.campaign-submission-notify]
verify_jwt = false

[functions.spotify-playlist-fetch]
verify_jwt = false